apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: express-trains
spec:
  # disable privileged containers and prevent privilege escalation  
  privileged: false
  allowPrivilegeEscalation: false
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    # Assume that persistentVolumes set up by the cluster admin are safe to use.
    - 'persistentVolumeClaim'
  # enable read only file system
  readOnlyRootFilesystem: true  
  # prevent containers from running as root
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'  
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535