# Note this is applied at run time to customize underlying image
# Underlying image doesn't therefore contain these files!
version: "2"
services:
  express-trains:
    build: .
    image: malminhas/express-trains:composed
    ports:
        - 8001
    volumes:
        - ./.transportAppId:/home/node/app/.transportAppId
        - ./.transportAppKey:/home/node/app/.transportAppKey
        - ./.README.md:/home/node/app/README.md
