// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trains.proto

package trains

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message
type TrainRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrainRequest) Reset()         { *m = TrainRequest{} }
func (m *TrainRequest) String() string { return proto.CompactTextString(m) }
func (*TrainRequest) ProtoMessage()    {}
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0af5513ca3cdfb34, []int{0}
}

func (m *TrainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrainRequest.Unmarshal(m, b)
}
func (m *TrainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrainRequest.Marshal(b, m, deterministic)
}
func (m *TrainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainRequest.Merge(m, src)
}
func (m *TrainRequest) XXX_Size() int {
	return xxx_messageInfo_TrainRequest.Size(m)
}
func (m *TrainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrainRequest proto.InternalMessageInfo

func (m *TrainRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TrainRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

// Response message
type TrainResponse struct {
	StationCode          string                          `protobuf:"bytes,1,opt,name=station_code,json=stationCode,proto3" json:"station_code,omitempty"`
	DestCode             string                          `protobuf:"bytes,2,opt,name=dest_code,json=destCode,proto3" json:"dest_code,omitempty"`
	Date                 string                          `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	TimeOfDay            string                          `protobuf:"bytes,4,opt,name=time_of_day,json=timeOfDay,proto3" json:"time_of_day,omitempty"`
	Departures           []*TrainResponse_TrainDeparture `protobuf:"bytes,5,rep,name=departures,proto3" json:"departures,omitempty"`
	StationName          string                          `protobuf:"bytes,6,opt,name=station_name,json=stationName,proto3" json:"station_name,omitempty"`
	DestName             string                          `protobuf:"bytes,7,opt,name=dest_name,json=destName,proto3" json:"dest_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *TrainResponse) Reset()         { *m = TrainResponse{} }
func (m *TrainResponse) String() string { return proto.CompactTextString(m) }
func (*TrainResponse) ProtoMessage()    {}
func (*TrainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0af5513ca3cdfb34, []int{1}
}

func (m *TrainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrainResponse.Unmarshal(m, b)
}
func (m *TrainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrainResponse.Marshal(b, m, deterministic)
}
func (m *TrainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainResponse.Merge(m, src)
}
func (m *TrainResponse) XXX_Size() int {
	return xxx_messageInfo_TrainResponse.Size(m)
}
func (m *TrainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrainResponse proto.InternalMessageInfo

func (m *TrainResponse) GetStationCode() string {
	if m != nil {
		return m.StationCode
	}
	return ""
}

func (m *TrainResponse) GetDestCode() string {
	if m != nil {
		return m.DestCode
	}
	return ""
}

func (m *TrainResponse) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *TrainResponse) GetTimeOfDay() string {
	if m != nil {
		return m.TimeOfDay
	}
	return ""
}

func (m *TrainResponse) GetDepartures() []*TrainResponse_TrainDeparture {
	if m != nil {
		return m.Departures
	}
	return nil
}

func (m *TrainResponse) GetStationName() string {
	if m != nil {
		return m.StationName
	}
	return ""
}

func (m *TrainResponse) GetDestName() string {
	if m != nil {
		return m.DestName
	}
	return ""
}

type TrainResponse_TrainStop struct {
	StationCode          string   `protobuf:"bytes,1,opt,name=station_code,json=stationCode,proto3" json:"station_code,omitempty"`
	StationName          string   `protobuf:"bytes,2,opt,name=station_name,json=stationName,proto3" json:"station_name,omitempty"`
	Platform             int32    `protobuf:"varint,3,opt,name=platform,proto3" json:"platform,omitempty"`
	ExpectedArrival      string   `protobuf:"bytes,4,opt,name=expected_arrival,json=expectedArrival,proto3" json:"expected_arrival,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrainResponse_TrainStop) Reset()         { *m = TrainResponse_TrainStop{} }
func (m *TrainResponse_TrainStop) String() string { return proto.CompactTextString(m) }
func (*TrainResponse_TrainStop) ProtoMessage()    {}
func (*TrainResponse_TrainStop) Descriptor() ([]byte, []int) {
	return fileDescriptor_0af5513ca3cdfb34, []int{1, 0}
}

func (m *TrainResponse_TrainStop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrainResponse_TrainStop.Unmarshal(m, b)
}
func (m *TrainResponse_TrainStop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrainResponse_TrainStop.Marshal(b, m, deterministic)
}
func (m *TrainResponse_TrainStop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainResponse_TrainStop.Merge(m, src)
}
func (m *TrainResponse_TrainStop) XXX_Size() int {
	return xxx_messageInfo_TrainResponse_TrainStop.Size(m)
}
func (m *TrainResponse_TrainStop) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainResponse_TrainStop.DiscardUnknown(m)
}

var xxx_messageInfo_TrainResponse_TrainStop proto.InternalMessageInfo

func (m *TrainResponse_TrainStop) GetStationCode() string {
	if m != nil {
		return m.StationCode
	}
	return ""
}

func (m *TrainResponse_TrainStop) GetStationName() string {
	if m != nil {
		return m.StationName
	}
	return ""
}

func (m *TrainResponse_TrainStop) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *TrainResponse_TrainStop) GetExpectedArrival() string {
	if m != nil {
		return m.ExpectedArrival
	}
	return ""
}

type TrainResponse_TrainDeparture struct {
	Mode         string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Service      string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	TrainUid     string `protobuf:"bytes,3,opt,name=train_uid,json=trainUid,proto3" json:"train_uid,omitempty"`
	Platform     int32  `protobuf:"varint,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Operator     string `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	OperatorName string `protobuf:"bytes,6,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`
	//string aimed_departure_time;
	//string aimed_arrival_time;
	//string aimed_pass_time;
	OriginName      string `protobuf:"bytes,7,opt,name=origin_name,json=originName,proto3" json:"origin_name,omitempty"`
	DestinationName string `protobuf:"bytes,8,opt,name=destination_name,json=destinationName,proto3" json:"destination_name,omitempty"`
	Source          string `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	//string category;
	//service_timetable: [Object],
	Status                string `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	ExpectedArrivalTime   string `protobuf:"bytes,11,opt,name=expected_arrival_time,json=expectedArrivalTime,proto3" json:"expected_arrival_time,omitempty"`
	ExpectedDepartureTime string `protobuf:"bytes,12,opt,name=expected_departure_time,json=expectedDepartureTime,proto3" json:"expected_departure_time,omitempty"`
	//string best_arrival_estimate_mins
	//string best_departure_estimate_mins
	Stops                []*TrainResponse_TrainStop `protobuf:"bytes,13,rep,name=stops,proto3" json:"stops,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TrainResponse_TrainDeparture) Reset()         { *m = TrainResponse_TrainDeparture{} }
func (m *TrainResponse_TrainDeparture) String() string { return proto.CompactTextString(m) }
func (*TrainResponse_TrainDeparture) ProtoMessage()    {}
func (*TrainResponse_TrainDeparture) Descriptor() ([]byte, []int) {
	return fileDescriptor_0af5513ca3cdfb34, []int{1, 1}
}

func (m *TrainResponse_TrainDeparture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrainResponse_TrainDeparture.Unmarshal(m, b)
}
func (m *TrainResponse_TrainDeparture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrainResponse_TrainDeparture.Marshal(b, m, deterministic)
}
func (m *TrainResponse_TrainDeparture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrainResponse_TrainDeparture.Merge(m, src)
}
func (m *TrainResponse_TrainDeparture) XXX_Size() int {
	return xxx_messageInfo_TrainResponse_TrainDeparture.Size(m)
}
func (m *TrainResponse_TrainDeparture) XXX_DiscardUnknown() {
	xxx_messageInfo_TrainResponse_TrainDeparture.DiscardUnknown(m)
}

var xxx_messageInfo_TrainResponse_TrainDeparture proto.InternalMessageInfo

func (m *TrainResponse_TrainDeparture) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *TrainResponse_TrainDeparture) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *TrainResponse_TrainDeparture) GetTrainUid() string {
	if m != nil {
		return m.TrainUid
	}
	return ""
}

func (m *TrainResponse_TrainDeparture) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *TrainResponse_TrainDeparture) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *TrainResponse_TrainDeparture) GetOperatorName() string {
	if m != nil {
		return m.OperatorName
	}
	return ""
}

func (m *TrainResponse_TrainDeparture) GetOriginName() string {
	if m != nil {
		return m.OriginName
	}
	return ""
}

func (m *TrainResponse_TrainDeparture) GetDestinationName() string {
	if m != nil {
		return m.DestinationName
	}
	return ""
}

func (m *TrainResponse_TrainDeparture) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *TrainResponse_TrainDeparture) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TrainResponse_TrainDeparture) GetExpectedArrivalTime() string {
	if m != nil {
		return m.ExpectedArrivalTime
	}
	return ""
}

func (m *TrainResponse_TrainDeparture) GetExpectedDepartureTime() string {
	if m != nil {
		return m.ExpectedDepartureTime
	}
	return ""
}

func (m *TrainResponse_TrainDeparture) GetStops() []*TrainResponse_TrainStop {
	if m != nil {
		return m.Stops
	}
	return nil
}

func init() {
	proto.RegisterType((*TrainRequest)(nil), "trains.TrainRequest")
	proto.RegisterType((*TrainResponse)(nil), "trains.TrainResponse")
	proto.RegisterType((*TrainResponse_TrainStop)(nil), "trains.TrainResponse.TrainStop")
	proto.RegisterType((*TrainResponse_TrainDeparture)(nil), "trains.TrainResponse.TrainDeparture")
}

func init() { proto.RegisterFile("trains.proto", fileDescriptor_0af5513ca3cdfb34) }

var fileDescriptor_0af5513ca3cdfb34 = []byte{
	// 634 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0x9c, 0x9f, 0x26, 0x93, 0xb4, 0x54, 0x0b, 0x05, 0xcb, 0x48, 0xb4, 0xa4, 0x1c, 0xda,
	0x8a, 0xc6, 0x90, 0x0a, 0x0e, 0x95, 0x90, 0x28, 0x44, 0xe2, 0x82, 0x40, 0x4a, 0xcb, 0xd9, 0xda,
	0xda, 0x1b, 0x67, 0x21, 0xf6, 0x2e, 0xbb, 0xeb, 0x42, 0xae, 0x3c, 0x02, 0x5c, 0x78, 0x2f, 0x0e,
	0xbc, 0x00, 0xcf, 0x81, 0x90, 0xc7, 0xeb, 0xd4, 0x49, 0x10, 0xe2, 0xe4, 0x99, 0x6f, 0x7e, 0xf6,
	0xf3, 0x37, 0xb3, 0x0b, 0x3d, 0xa3, 0x28, 0x4f, 0xf5, 0x40, 0x2a, 0x61, 0x04, 0x69, 0x15, 0x9e,
	0x77, 0x62, 0xa6, 0x5c, 0x45, 0x81, 0xa4, 0xca, 0xcc, 0xfd, 0x58, 0x88, 0x78, 0xc6, 0xa8, 0xe4,
	0xda, 0x9a, 0x3e, 0x95, 0xdc, 0xa7, 0x69, 0x2a, 0x0c, 0x35, 0x5c, 0x94, 0xc5, 0xde, 0x43, 0xfc,
	0x84, 0xc7, 0x31, 0x4b, 0x8f, 0xf5, 0x27, 0x1a, 0xc7, 0x4c, 0xf9, 0x42, 0x62, 0xc6, 0x7a, 0x76,
	0x7f, 0x08, 0xbd, 0x8b, 0xfc, 0xb0, 0x31, 0xfb, 0x98, 0x31, 0x6d, 0x08, 0x81, 0xc6, 0x44, 0x89,
	0xc4, 0xad, 0xed, 0xd5, 0x0e, 0x3a, 0x63, 0xb4, 0xc9, 0x16, 0x38, 0x46, 0xb8, 0x0e, 0x22, 0x8e,
	0x11, 0xfd, 0xdf, 0x2d, 0xd8, 0xb4, 0x45, 0x5a, 0x8a, 0x54, 0x33, 0x72, 0x1f, 0x7a, 0xba, 0xe8,
	0x1b, 0x84, 0x22, 0x62, 0xb6, 0xba, 0x6b, 0xb1, 0x97, 0x22, 0x62, 0xe4, 0x2e, 0x74, 0x22, 0xa6,
	0x4d, 0x11, 0x2f, 0x7a, 0xb5, 0x73, 0x00, 0x83, 0x04, 0x1a, 0x11, 0x35, 0xcc, 0xad, 0x17, 0xa7,
	0xe6, 0x36, 0xb9, 0x07, 0x5d, 0xc3, 0x13, 0x16, 0x88, 0x49, 0x10, 0xd1, 0xb9, 0xdb, 0xc0, 0x50,
	0x27, 0x87, 0xde, 0x4e, 0x46, 0x74, 0x4e, 0x46, 0x00, 0x11, 0xcb, 0xa5, 0xc9, 0x14, 0xd3, 0x6e,
	0x73, 0xaf, 0x7e, 0xd0, 0x1d, 0x3e, 0x18, 0x58, 0x1d, 0x97, 0xe8, 0x15, 0xde, 0xa8, 0x4c, 0x1e,
	0x57, 0xea, 0xaa, 0xcc, 0x53, 0x9a, 0x30, 0xb7, 0xb5, 0xc4, 0xfc, 0x0d, 0x4d, 0xae, 0x99, 0x63,
	0x7c, 0xe3, 0x9a, 0x79, 0x1e, 0xf4, 0xbe, 0xd7, 0xa0, 0x83, 0xed, 0xcf, 0x8d, 0x90, 0xff, 0xa3,
	0xc3, 0xea, 0x81, 0xce, 0xfa, 0x81, 0x1e, 0xb4, 0xe5, 0x8c, 0x9a, 0x89, 0x50, 0x09, 0x2a, 0xd2,
	0x1c, 0x2f, 0x7c, 0x72, 0x08, 0xdb, 0xec, 0xb3, 0x64, 0xa1, 0x61, 0x51, 0x40, 0x95, 0xe2, 0x57,
	0x74, 0x66, 0xa5, 0xb9, 0x51, 0xe2, 0x67, 0x05, 0xec, 0xfd, 0xac, 0xc3, 0xd6, 0xf2, 0x9f, 0xe7,
	0x3a, 0x27, 0xd7, 0xbc, 0xd0, 0x26, 0x2e, 0x6c, 0x68, 0xa6, 0xae, 0x78, 0x58, 0x72, 0x29, 0xdd,
	0xfc, 0xc7, 0x51, 0xce, 0x20, 0xe3, 0x91, 0x1d, 0x4d, 0x1b, 0x81, 0x77, 0x3c, 0x5a, 0x22, 0xd9,
	0x58, 0x21, 0xe9, 0x41, 0x5b, 0x48, 0xa6, 0xa8, 0x11, 0xca, 0x6d, 0x16, 0x75, 0xa5, 0x4f, 0xf6,
	0x61, 0xb3, 0xb4, 0xab, 0x8a, 0xf7, 0x4a, 0x10, 0x15, 0xd8, 0x85, 0xae, 0x50, 0x3c, 0xe6, 0x69,
	0x55, 0x74, 0x28, 0x20, 0x4c, 0x38, 0x84, 0xed, 0x7c, 0x04, 0x3c, 0xad, 0x28, 0xd9, 0x2e, 0x64,
	0xa8, 0xe0, 0x98, 0x7a, 0x1b, 0x5a, 0x5a, 0x64, 0x2a, 0x64, 0x6e, 0x07, 0x13, 0xac, 0x87, 0xb8,
	0xa1, 0x26, 0xd3, 0x2e, 0x58, 0x1c, 0x3d, 0x32, 0x84, 0x9d, 0x55, 0x85, 0x83, 0x7c, 0xeb, 0xdc,
	0x2e, 0xa6, 0xdd, 0x5c, 0x91, 0xf9, 0x82, 0x27, 0x8c, 0x3c, 0x85, 0x3b, 0x8b, 0x9a, 0xc5, 0x72,
	0x15, 0x55, 0x3d, 0xac, 0x5a, 0xb4, 0x5c, 0xcc, 0x02, 0xeb, 0x9e, 0x40, 0x53, 0x1b, 0x21, 0xb5,
	0xbb, 0x89, 0xeb, 0xbb, 0xfb, 0x8f, 0xf5, 0xcd, 0xf7, 0x6b, 0x5c, 0x64, 0x0f, 0x2f, 0xec, 0xa5,
	0x3d, 0xb7, 0x83, 0x1a, 0x41, 0xe7, 0x15, 0x33, 0x08, 0x69, 0x72, 0x6b, 0xa5, 0x09, 0xde, 0x6b,
	0x6f, 0xe7, 0xaf, 0xad, 0xfb, 0xf0, 0xe5, 0xc7, 0xaf, 0x6f, 0x4e, 0x83, 0x38, 0xfe, 0xd1, 0x8b,
	0xf9, 0xd7, 0xb3, 0x2b, 0xf2, 0x1a, 0xec, 0xe3, 0xd3, 0x7f, 0x56, 0x5a, 0x64, 0x7f, 0x6a, 0x8c,
	0xd4, 0xa7, 0xbe, 0x1f, 0x73, 0x33, 0xcd, 0x2e, 0x07, 0xa1, 0x48, 0xfc, 0x84, 0xce, 0x12, 0x9e,
	0x4e, 0xa9, 0xf6, 0xed, 0x5b, 0xb5, 0x95, 0xd0, 0xd9, 0xf3, 0x1c, 0x1d, 0x84, 0x62, 0x90, 0x7d,
	0x18, 0xd6, 0x1f, 0x0f, 0x1e, 0x1d, 0x39, 0x35, 0x67, 0xb8, 0x4d, 0xa5, 0x9c, 0xf1, 0x10, 0x07,
	0xe2, 0xbf, 0xd7, 0x22, 0x3d, 0x5d, 0x43, 0x2e, 0x5b, 0xf8, 0x18, 0x9d, 0xfc, 0x09, 0x00, 0x00,
	0xff, 0xff, 0x9d, 0x11, 0x3b, 0xf9, 0x07, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TrainServiceClient is the client API for TrainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrainServiceClient interface {
	GetTrains(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (*TrainResponse, error)
}

type trainServiceClient struct {
	cc *grpc.ClientConn
}

func NewTrainServiceClient(cc *grpc.ClientConn) TrainServiceClient {
	return &trainServiceClient{cc}
}

func (c *trainServiceClient) GetTrains(ctx context.Context, in *TrainRequest, opts ...grpc.CallOption) (*TrainResponse, error) {
	out := new(TrainResponse)
	err := c.cc.Invoke(ctx, "/trains.TrainService/GetTrains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainServiceServer is the server API for TrainService service.
type TrainServiceServer interface {
	GetTrains(context.Context, *TrainRequest) (*TrainResponse, error)
}

// UnimplementedTrainServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTrainServiceServer struct {
}

func (*UnimplementedTrainServiceServer) GetTrains(ctx context.Context, req *TrainRequest) (*TrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrains not implemented")
}

func RegisterTrainServiceServer(s *grpc.Server, srv TrainServiceServer) {
	s.RegisterService(&_TrainService_serviceDesc, srv)
}

func _TrainService_GetTrains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainServiceServer).GetTrains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trains.TrainService/GetTrains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainServiceServer).GetTrains(ctx, req.(*TrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TrainService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trains.TrainService",
	HandlerType: (*TrainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrains",
			Handler:    _TrainService_GetTrains_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trains.proto",
}
