apiVersion: v1
kind: Service
metadata:
  labels:
    app: express-trains
  name: express-trains
spec:
  type: LoadBalancer
  selector:
    app: express-trains
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
      name: http
