apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: express-trains
  name: express-trains
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-trains
  template:
    metadata:
      labels:
        app: express-trains
    spec:
      containers:
      - name: express-trains
        image: malminhas/express-trains:composed
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          protocol: TCP
        securityContext:
          #runAsUser: node
          #runAsGroup: 3000
          #fsGroup: 2000
          allowPrivilegeEscalation: false
        env:
          - name: TRANSPORTAPPID
            valueFrom:
              secretKeyRef:
                name: express-trains-credentials
                key: appId
          - name: TRANSPORTAPPKEY
            valueFrom:
              secretKeyRef:
                name: express-trains-credentials
                key: appKey
